# Conexão Dinâmica (Configurada para o Railway)
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate
spring.jpa.show-sql=true
# 'update' cria as tabelas automaticamente se elas não existirem
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Porta Dinâmica (O Railway decide em qual porta o app vai rodar)
server.port=${PORT:8080}






#--- CONFIGURAÇÃO DO SERVIDOR ---
#Porta padrão para rodar no seu computador
#server.port=8080

# --- CONFIGURAÇÃO DO BANCO DE DADOS (LOCAL) ---
# O nome do banco conforme seu print: barbearia_chaplin
# O parâmetro 'createDatabaseIfNotExist' garante que o Spring crie o banco se ele sumir
#spring.datasource.url=jdbc:mysql://localhost:3306/barbearia_chaplin?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=xxxx#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- CONFIGURAÇÕES DO HIBERNATE / JPA ---
# 'update' cria ou atualiza as tabelas automaticamente sem apagar seus dados
#spring.jpa.hibernate.ddl-auto=update

# Mostra no console as consultas SQL que o Java está fazendo (bom para debug)
#spring.jpa.show-sql=true

# Dialeto específico para o MySQL 8
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# --- CONFIGURAÇÃO DE INICIALIZAÇÃO ---
# Garante que o Hibernate não tente criar as tabelas antes da conexão estar pronta
#spring.jpa.defer-datasource-initialization=true

# Caso você use um arquivo 'data.sql' para popular o banco
#spring.sql.init.mode=always
