# Conexão Dinâmica (Lê as variáveis do Railway)
spring.datasource.url=jdbc:mysql://${SPRING_DATASOURCE_URL:localhost:3306/barbearia_chaplin}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1005GUga#}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Porta Dinâmica (Obrigatório para o Railway)
server.port=${PORT:8080}